[package]
name = "erc1820-registry"
version = "0.1.0"
edition = "2018"

[dependencies]
casper-contract = "1.3.2"
casper-erc1820 = { path = "../../../erc1820" }
casper-types = "1.3.2"

[[bin]]
name = "erc1820_registry"
path = "src/main.rs"
bench = false
doctest = false
test = false
